{
 "title": "Log Ingestor Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Normal Insertion",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{route=\"/public/ingest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion using Prepared Statement",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{route=\"/public/ingest-prepared-stmt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion Via Kafka",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{route=\"/public/ingest-kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(route, le) (rate(http_response_time_seconds_bucket{route!=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}